export function start(type) {
    return {
        type
    }
}

export function succes(type, data) {
    return {
        type,
        data
    }
}

export function failure(type, error) {
    return {
        type,
        error
    }
}

export const FETCHING_TOP = "FETCHING_TOP"
export const FETCHING_TOP_SUCCES = "FETCHING_TOP_SUCCES"
export const FETCHING_TOP_FAILURE = "FETCHING_TOP_FAILURE"

export const FETCHING_DETAILS = "FETCHING_DETAILS"
export const FETCHING_DETAILS_SUCCES = "FETCHING_DETAILS_SUCCES"
export const FETCHING_DETAILS_FAILURE = "FETCHING_DETAILS_FAILURE"

export const FETCHING_EPISODES = "FETCHING_EPISODES"
export const FETCHING_EPISODES_SUCCES = "FETCHING_EPISODES_SUCCES"
export const FETCHING_EPISODES_FAILURE = "FETCHING_EPISODES_FAILURE"

export const FETCHING_EPISODE = "FETCHING_EPISODE"
export const FETCHING_EPISODE_SUCCES = "FETCHING_EPISODE_SUCCES"
export const FETCHING_EPISODE_FAILURE = "FETCHING_EPISODE_FAILURE"

export const FETCHING_SEARCH = "FETCHING_SEARCH"
export const FETCHING_SEARCH_SUCCES = "FETCHING_SEARCH_SUCCES"
export const FETCHING_SEARCH_FAILURE = "FETCHING_SEARCH_FAILURE"

export const FAVORITES_GET = "FAVORITES_GET"
export const FAVORITES_GET_SUCCES = "FAVORITES_GET_SUCCES"
export const FAVORITES_GET_FAILURE = "FAVORITES_GET_FAILURE"

export const FAVORITES_SET = "FAVORITES_SET"
export const FAVORITES_SET_SUCCES = "FAVORITES_SET_SUCCES"
export const FAVORITES_SET_FAILURE = "FAVORITES_SET_FAILURE"

export const FAVORITES_CHECK = "FAVORITES_CHECK"
export const FAVORITES_CHECK_SUCCES = "FAVORITES_CHECK_SUCCES"
export const FAVORITES_CHECK_FAILURE = "FAVORITES_CHECK_FAILURE"

export const FAVORITES_ADD = "FAVORITES_ADD"
export const FAVORITES_ADD_SUCCES = "FAVORITES_ADD_SUCCES"
export const FAVORITES_ADD_FAILURE = "FAVORITES_ADD_FAILURE"

export const FAVORITES_REMOVE = "FAVORITES_REMOVE"
export const FAVORITES_REMOVE_SUCCES = "FAVORITES_REMOVE_SUCCES"
export const FAVORITES_REMOVE_FAILURE = "FAVORITES_REMOVE_FAILURE"

export const WATCHED_GET = "WATCHED_GET"
export const WATCHED_GET_SUCCES = "WATCHED_GET_SUCCES"
export const WATCHED_GET_FAILURE = "WATCHED_GET_FAILURE"

export const WATCHED_SET = "WATCHED_SET"
export const WATCHED_SET_SUCCES = "WATCHED_SET_SUCCES"
export const WATCHED_SET_FAILURE = "WATCHED_SET_FAILURE"

export const WATCHED_CHECK = "WATCHED_CHECK"
export const WATCHED_CHECK_SUCCES = "WATCHED_CHECK_SUCCES"
export const WATCHED_CHECK_FAILURE = "WATCHED_CHECK_FAILURE"

export const WATCHED_ADD = "WATCHED_ADD"
export const WATCHED_ADD_SUCCES = "WATCHED_ADD_SUCCES"
export const WATCHED_ADD_FAILURE = "WATCHED_ADD_FAILURE"

export const WATCHED_REMOVE = "WATCHED_REMOVE"
export const WATCHED_REMOVE_SUCCES = "WATCHED_REMOVE_SUCCES"
export const WATCHED_REMOVE_FAILURE = "WATCHED_REMOVE_FAILURE"

export const UPDATE = "UPDATE"
export const UPDATE_SUCCES = "UPDATE_SUCCES"
export const UPDATE_FAILURE = "UPDATE_FAILURE"