export const FETCHING_TOP = "FETCHING_TOP"
export const FETCHING_TOP_SUCCES = "FETCHING_TOP_SUCCES"
export const FETCHING_TOP_FAILURE = "FETCHING_TOP_FAILURE"

export const FETCHING_DETAILS = "FETCHING_DETAILS"
export const FETCHING_DETAILS_SUCCES = "FETCHING_DETAILS_SUCCES"
export const FETCHING_DETAILS_FAILURE = "FETCHING_DETAILS_FAILURE"

export const FETCHING_EPISODES = "FETCHING_EPISODES"
export const FETCHING_EPISODES_SUCCES = "FETCHING_EPISODES_SUCCES"
export const FETCHING_EPISODES_FAILURE = "FETCHING_EPISODES_FAILURE"

export const FETCHING_EPISODE = "FETCHING_EPISODE"
export const FETCHING_EPISODE_SUCCES = "FETCHING_EPISODE_SUCCES"
export const FETCHING_EPISODE_FAILURE = "FETCHING_EPISODE_FAILURE"

export const FETCHING_SEARCH = "FETCHING_SEARCH"
export const FETCHING_SEARCH_SUCCES = "FETCHING_SEARCH_SUCCES"
export const FETCHING_SEARCH_FAILURE = "FETCHING_SEARCH_FAILURE"

export const FAVORITES_GET = "FAVORITES_GET"
export const FAVORITES_GET_SUCCES = "FAVORITES_GET_SUCCES"
export const FAVORITES_GET_FAILURE = "FAVORITES_GET_FAILURE"

export const FAVORITES_SET = "FAVORITES_SET"
export const FAVORITES_SET_SUCCES = "FAVORITES_SET_SUCCES"
export const FAVORITES_SET_FAILURE = "FAVORITES_SET_FAILURE"